version: "3.8"

services:
  rabbitmq:
    image: "rabbitmq:3.8-management-alpine"
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "./.rabbitmq_data:/var/lib/rabbitmq/mnesia"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  api-b:
    build:
      context: "./api-b"
      dockerfile: Dockerfile
    restart: always
    container_name: api-b
    links:
      - rabbitmq
    volumes:
      - ./api-b:/home/node/app
    ports:
      - 3001:3001
    depends_on:
      - rabbitmq

  api-a:
    build:
      context: "./api-a"
      dockerfile: Dockerfile
    restart: always
    container_name: api-a
    links:
      - rabbitmq
    volumes:
      - ./api-a:/home/node/app
    ports:
      - 3000:3000
    depends_on:
      - rabbitmq
      - api-b
