version: "3.8"

services:
  # rabbitmq:
  #   image: rabbitmq:3-management-alpine
  #   container_name: 'rabbitmq'
  #   ports:
  #       - 5672:5672
  #       - 15672:15672
  #   volumes:
  #       - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
  #       - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  #   networks:
  #       - rabbitmq_net

  api-a:
    build:
      context: "./api-a"
      dockerfile: Dockerfile
    container_name: typescript-container
    restart: always
    volumes:
      - ./api-a:/home/node/app
    ports:
      - 3000:3000
    networks:
        - rabbitmq_net

  api-b:
    build:
      context: "./api-b"
      dockerfile: Dockerfile
    container_name: javascript-container
    restart: always
    volumes:
      - ./api-b:/home/node/app
    ports:
      - 3001:3001
    networks:
        - rabbitmq_net

networks:
  rabbitmq_net:
    driver: bridge
